name: terminal-resume
   static_sites:
     - name: web
       github:
         repo: eneameta/enea-resume
         branch: main
       source_dir: /
       index_document: terminal-resume.html
       output_dir: /
